# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
name: Build Container
description: Given the inputs found below, build all containers found in a docker-compose.yaml file for a given configuration
inputs:
  work_dir:
    description: Directory to run the build in
    required: true
    type: string
  docker_compose_path:
    description: Path with xxx-compose.yaml to build
    required: true
    type: string
  service_list:
    description: List of services to build
    required: false
    default: ""
    type: string
  registry:
    description: Container Registry URL
    required: false
    default: "opea"
    type: string
  tag:
    description: Container Tag
    required: false
    default: "latest"
    type: string

runs:
  using: "composite"
  steps:
    - name: Build Containers
      shell: bash
      run: |
        service_list=$(echo ${{ inputs.service_list }} | tr ',' ' ')
        echo $service_list
        cp ${{ inputs.docker_compose_path }} ${{ inputs.work_dir }}/docker-compose.yaml
        REGISTRY=${{ inputs.registry }} \
        TAG=${{ inputs.tag }} \
        docker compose build ${service_list} --no-cache
      working-directory: ${{ inputs.work_dir }}
    - name: Push Containers
      shell: bash
      run: |
        service_list=$(echo ${{ inputs.service_list }} | tr ',' ' ')
        REGISTRY=${{ inputs.registry }} \
        TAG=${{ inputs.tag }} \
        docker compose push ${service_list}
      working-directory: ${{ inputs.work_dir }}
    - name: Clean up Containers
      if: ${{ always() }}
      shell: bash
      run: |
        REGISTRY=${{ inputs.registry }} \
        TAG=${{ inputs.tag }} \
        docker compose down --rmi all
      working-directory: ${{ inputs.work_dir }}
    - name: Remove Containers
      if: ${{ always() }}
      shell: bash
      run: docker system prune --force
